#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"

case "$(echo $@)" in

  "")
    node -e "console.log(process.env);"
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

