#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  watch)
    local +x CMD="my_typescript scratch run"
    cd "$THIS_DIR"
    mkdir -p tmp/scratch
    ${=CMD} || :
    process watch "-r sh -r bin -r tmp/scratch" "my_typescript scratch run"
    ;;

  run)
    cd "$THIS_DIR"/tmp/scratch
    sh_color ORANGE "=== {{Compiling}}..."
    tsc scratch.ts --outDir "$THIS_DIR"/tmp --allowJs --sourceMap --removeComments --strict --strictNullChecks --alwaysStrict
    rollup "$THIS_DIR"/tmp/scratch.js --o "$THIS_DIR"/tmp/scratch.bundle.js --f cjs
    sh_color ORANGE "=== {{Running}}..."
    node ../scratch.bundle.js
    sh_color GREEN "=== {{DONE}} ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

